### ISSUE TITLE
problem ApproxSpline.Surf2d.derivative function

### ISSUE THREAD

**Issue by FrancNep** [modelica-3rdparty/ApproxSpline#2]
Hi,

I would like to use ApproxSpline library to develop a media package based on spline interpolation with 2d thermodynamic tables, typically for example h=f(p,T).

"Surf2d.eval" function works fine using rectangular table but i have an error "parder returns err: ierr=10 " with "Surf2d.derivative" function.

 h =ApproxSpline.Surf2d.eval(
     spline_h_pT,
     x=p_var.y,
     y=T_var.y);  -->OK

//Cp calculation dh/dT 
 Cp =ApproxSpline.Surf2d.derivative(
      spline_h_pT,
      x=p_var.y,
      y=T_var.y,
      ddx=0,
      ddy=1); -->error "parder returns err: ierr=10 " 

I checked the mdc_dierck.c and the parder.f but without succes...

Any idea?

Thanks  in advance,

François

**Comment by beutlich** [comment]
I can only guess that the input data is not valid:

https://github.com/modelica-3rdparty/ApproxSpline/blob/28420f5c1a88c9cd069defbd8c05e4a78a090675/ApproxSpline/Resources/C-Sources/dierckx/parder.c#L81-L87

**Comment by FrancNep** [comment]
Hi,

I guess  the problem is due to smoothness parameter s  and a bad dimensionless/value of the matrix tx and/or ty.
If tx and ty are user- defined inputs of ApproxSpline.Surf2d.derivative, it works fine.

**Comment by FrancNep** [comment]
The error comes from mdc_Dierckx.c . into the both functions surf2dScatNew and surf2dRectNew
surf->lwrk = MX_MAX*(kx)+MY_MAX*(ky)+((surf->nx)-kx-1)*((surf->ny)-ky-1);
replacing
surf->lwrk = MX_MAX*(kx)+MY_MAX*(ky)+(nx-kx-1)*(ny-ky-1);

Thanks for this fine library.

**Comment by overtaker** [comment]
Thanks. Finally fixed as proposed.
